### ISSUE TITLE
Missing Recipe for "Regions Unexplored" Logs for Stripped Logs

### ISSUE THREAD

**Issue by SakulFlee** [OpenPlayVerse/ProjectCreate#4] opened 2024-10-20 20:06 UTC
Dropping a Log (unstripped) on a running _Mechanised Saw_ should result in _Stripped Logs_ coming out from it.
Instead, _Cast Moulds_ are dropped.

Setting the item filter on the _Mechanised Saw_ makes it simply drop the initial Log, unstripped.

**Comment by Namelessys** [comment] 2024-10-22 09:25
Could not reproduce the bug. If i'll drop an log without item filter a random recipe gets "crafted" just as intended. Item filter works fine as well. 

Are you sure u have the same striped log in the filter as you want to craft?
The only scenario i get the described behavior is when I have an striped oak log and try to saw a birch wood log for example.

**Comment by SakulFlee** [comment] 2024-10-22 14:19
Correction!
It **does** work fine with any Vanilla tree logs.
It **breaks** with any _Region Unexplored_ logs!

See the video (think I didn't mute xD):
https://youtu.be/arnCGa8dtjk
(might still be processing)

Been showing the following:
1. _Region Unexplored_ Logs without filter -> Cast Mould
2. _Region Unexplored_ Logs with filter -> Returns the Log
3. _Region Unexplored_ Logs with Log filter -> Returns the Log (as it should)
4. _Vanilla_ Logs without filter -> Cast Mould
5. _Vanilla_ Logs with filter -> Stripped logs! :)

**Comment by Namelessys** [comment] 2024-10-24 08:21
The issue seems to be 'Silver Birch Log' specific as there is no stripped version of that block. If stripped by an axe it is converted into an vanilla 'Stripped Birch Log'.
Every other RE log ive testet works fine.
Issue is fixed in [v0.22](https://github.com/OpenPlayVerse/ProjectCreate/releases/tag/0.22).

**Closed as completed by Namelessys** 2024-10-24 08:21 UTC
